### ISSUE TITLE
Consider basing version number on slf4j version

### ISSUE THREAD

**Issue by stephenh** [FinamTrade/slf4j-gwt#1]
E.g. if slf4j-gwt implements slf4j 1.7.6, then perhaps have the slf4j-gwt version be 1.7.6.0.

This way you could do bug fixes (e.g. 1.7.6.1, 1.7.6.2) but then it'd also be immediately apparent to users which version of slf4j-gwt matches which version of slf4j.

(We've had some bad experiences with slf4j 1.6 vs. slf4j 1.7 getting on the classpath, so are just very concerned about slf4j versions always matching.)

(But this looks great; I haven't tried it in our GWT project yet, but will soon. Thanks for putting it together!)

**Comment by korzha** [comment]
Sounds reasonable. Thanks, Stephen!

**Comment by korzha** [comment]
done

**Comment by stephenh** [comment]
Cool, thanks!

**Comment by korzha** [comment]
You're welcome! I fixed it months ago but forgot to close the issue :)
